name: Build and publish a Wasm Component to GitHub Artifacts

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  COMPONENT_NAME: wordmark
  COMPONENT_DESCRIPTION: "Convert between Markdown and Word documents"
  COMPONENT_SOURCE: "https://github.com/yoshuawuyts/components"
  COMPONENT_HOMEPAGE: "https://github.com/yoshuawuyts/components"
  COMPONENT_LICENSES: "MIT OR Apache-2.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.15

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.actor }}/${{ env.COMPONENT_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache cargo bin
        id: cache-cargo
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-bin
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        name: Install build dependencies
        continue-on-error: false
        run: |
          cargo binstall wkg --force

      - name: Add wasm32-wasip2 target
        run: rustup target add wasm32-wasip2

      - name: Build the component
        run: cargo build --release --target wasm32-wasip2

      - name: Normalize COMPONENT_NAME and Append .wasm
        run: echo "COMPONENT_NAME_UNDERSCORED=${COMPONENT_NAME//-/_}.wasm" >> $GITHUB_ENV

      - name: Publish `:<version>` to GitHub Container Registry
        if: github.event_name != 'workflow_dispatch'
        id: publish_versioned
        uses: bytecodealliance/wkg-github-action@v5
        with:
          file: target/wasm32-wasip2/release/${{ env.COMPONENT_NAME_UNDERSCORED }}
          oci-reference-without-tag: ghcr.io/${{ env.IMAGE_NAME }}/${{ env.COMPONENT_NAME }}
          version: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          description: ${{ env.COMPONENT_DESCRIPTION }}
          source: ${{ env.COMPONENT_SOURCE }}
          homepage: ${{ env.COMPONENT_HOMEPAGE }}
          licenses: ${{ env.COMPONENT_LICENSES }}
